<a href="https://colab.research.google.com/github/majorquev/DBDC_202010_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/Clase2/Clase_2_01_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Jorge Arévalo Labarca <br>
**E-mail ayudante:** jorge.arevalol@usach.cl



### 3.2 Matrices

En R, así como en otros lenguajes de programación, una maztriz es básicamente un arreglo bi-dimensional, donde las entradas horizontales se entienden como filas y las verticales como columnas. Es posible imaginar una matriz como un arreglo de vectores como columnas (o filas) del mismo largo.

 * ¿Qué se guarda en una matriz?<br>
    Sólo datos de un mismo tipo. 
     
 * ¿Cómo se declara una matriz?<br>
    Se puede definir de varias maneras, indicando los elementos que la componen, o combinando vectores como filas o columnas.
 
 * ¿Cómo se accede a sus elementos?<br>
    Indicando la posición del vector fila, seguido de la posición del vector columna (como es usual).

In [6]:
# 3.2 Matrices ------------
#?matrix de dos filas y 3 columnas, parametros ncol, nrow y byrow
# recibe un vector de elementos
M1 <- matrix(c(1,2,3,4,5,6), ncol = 3, nrow = 2)
M2 <- matrix(c(1,2,3,4,5,6), ncol = 3, nrow = 2, byrow = TRUE)

M1
M2


[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [9]:
# clase y atributo dim
class(M1)
dim(M1)

[1] "matrix" "array"

[1] 2 3

In [13]:
# Genere dos vectores del mismo largo y forme una matriz.

v1 <- c(1,1,2,3)
v2 <- c(10,20,30,40)
v3 <- -5:-2

v1
v2
v3


[1] 1 1 2 3

[1] 10 20 30 40

[1] -5 -4 -3 -2

In [14]:
# funciones cbind() [une vectores como columnas]
# y rbind() [une vectores como filas] (pensadas para matrices)
#?cbind

M4 <- cbind(v1,v2,v3)
M4



v1 v2 v3
[1,] 1  10 -5
[2,] 1  20 -4
[3,] 2  30 -3
[4,] 3  40 -2

In [15]:
# si combinamos vectores de distinto largo?
# R recicla valores (recordar explicación)

rbind(v1, c(11,12,13,14,15))


Warning message in rbind(v1, c(11, 12, 13, 14, 15)):
“number of columns of result is not a multiple of vector length (arg 1)”


[,1] [,2] [,3] [,4] [,5]
v1  1    1    2    3    1  
   11   12   13   14   15

In [16]:
# función diag para la definición de matrices diagonales
#?diag 

diag(c(1,2,3,4,5,6,9))


[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 1    0    0    0    0    0    0   
[2,] 0    2    0    0    0    0    0   
[3,] 0    0    3    0    0    0    0   
[4,] 0    0    0    4    0    0    0   
[5,] 0    0    0    0    5    0    0   
[6,] 0    0    0    0    0    6    0   
[7,] 0    0    0    0    0    0    9

In [22]:
# Podemos acceder a los elementos de una matriz
# indicando la posición de la fila y la columna de la casilla correspondiente.
# Ejemplo:
M2
# quiero rescatar el elemento "(2,1)"
M2[2,1]

# CUIDADO:No es lo mismo que 
M2[c(2,1)] # R entiende también la matriz como un gran vector (por columnas) y lo anterior retorna los elmentos 2 y 1 de dicho vector

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

[1] 4

[1] 4 1

In [24]:
# Para acceder a una fila completa
M2[1,]


# Para acceder a una columna completa
M2[,2]


[1] 1 2 3

[1] 2 5

In [25]:
#Recordemos que podemos actualizar elementos de un vector como:

# quiero cambiar el 5 por un 99 (el 5 de la pos 2,2)
M2
M2[2,2] <- 99




[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [26]:
M2

[,1] [,2] [,3]
[1,] 1     2   3   
[2,] 4    99   6

In [28]:
# Acceso mediante nombres

colnames(M2)
rownames(M2)





NULL

NULL

In [33]:
colnames(M2) <- c("c1","c2","c3")
rownames(M2) <- c("f1","f2")


In [34]:
M2

c1 c2 c3
f1 1   2 3 
f2 4  99 6

In [35]:
# Acceso mediante nomnbres


M2["f2","c2"]


[1] 99

In [37]:
M2[,c("c2","c1")]
M2[,c(2,1)]

c2 c1
f1  2 1 
f2 99 4

c2 c1
f1  2 1 
f2 99 4

In [39]:
M2

c1 c2 c3
f1 1   2 3 
f2 4  99 6

In [41]:
# Acceso mediante "indicatrices" lógicas 
#Quiero obtener los elementos (1,1) y (2,3) de M2
# 1: Crear una matriz de 2x3 con TRUE en dichas posiciones y FALSE en las restantes.

ind <- matrix(c(T,F,F,F,F,T), ncol = 3, nrow = 2, byrow = T)
ind


[,1]  [,2]  [,3] 
[1,]  TRUE FALSE FALSE
[2,] FALSE FALSE  TRUE

In [50]:
# pregunta de Patricio
which(ind[1,])
which(ind[2,])


which(ind, arr.ind = T)  #esto sirve


[1] 1

[1] 3

In [49]:
which(ind[,1])
which(ind[,2])
which(ind[,3])

[1] 1

integer(0)

[1] 2

In [42]:
# Podemos evaluar las casillas de una atriz mediante sentencias lógicas

M2[ind]

[1] 1 6

row col
[1,] 1   1  
[2,] 2   3

In [43]:
M2 >= 6

c1    c2    c3   
f1 FALSE FALSE FALSE
f2 FALSE  TRUE  TRUE

In [44]:
M2[M2 >= 6]

[1] 99  6

**Álgebra de matrices**

Las operaciones suma (resta) y ponderación por escalar se llevan cabo mediante los mismos operadores utilizados para valores numéricos y vectores (+,-,*, /). Para multiplicar matrices en cambio, se utiliza el operador %*%, mientras que para invertirlas se utiliza la función solve(), t() para transponer y det() para el cálculo del determinante en el caso de matrices cuadradas.

In [54]:
# transponer una matriz
t(M2)

f1 f2
c1 1   4
c2 2  99
c3 3   6

In [56]:
# 3.2 Álgbra de matrices  ------------
# Ejemplo simple de álgebra de matrices

M2 +  M1


c1 c2  c3
f1 2    5  8
f2 6  103 12

In [57]:
# Multiplicación de matrices
M2 * M1 # multiplicación componente a componente



c1 c2  c3
f1 1    6 15
f2 8  396 36

In [59]:
A <- M2 %*% t(M1) # multiplicación componente a componente
A

[,1] [,2]
f1  22   28 
f2 331  440

In [60]:
# podemos calcular determinantes
# ?det

det(A) 


[1] 412

In [61]:
# Podemos invertir matrices
# ?solve
solve(A)

f1         f2         
[1,]  1.0679612 -0.06796117
[2,] -0.8033981  0.05339806